### ISSUE TITLE
Ubuntu 16.04 does not see SIS-PMS device

### ISSUE THREAD

**Issue by papachappa** [xypron/sispmctl#2] opened 2017-12-08 15:45 UTC
Hello! We have Silver shield Gembird SIS-PMS device. But when we plugged it in our Ubuntu 16.04 via usb and trying lsusb -t there is nothing about Gembird. sudo sispmctl -g 1 says "No GEMBIRD SiS-PM found. Check USB connections, please!"
dmesg | grep usb | grep -i gemb
also output nothing. Version of sispmctl is 4.0
Made a reboot of the Ubuntu - the same situation. Could you please give a suggestion what is wrong?

**Comment by xypron** [comment] 2017-12-08 16:14
@papachappa 

My power socket is shown by lsusb as
Bus 001 Device 004: ID 04b4:fd13 Cypress Semiconductor Corp. Programmable power socket

Please, execute lsusb with the Gembird usb connector plugged in and without the Gembird. This should let you identify the lsusb output line asscociated with your device.

Could you, please, send me this line.

Heinrich Schuchardt <xypron.glpk@gmx.de>

**Comment by papachappa** [comment] 2017-12-09 14:12
Yeah, we have already issued command lsusb, and have already replugged device via different usb ports but result is the same - "No GEMBIRD SiS-PM found. Check USB connections, please!" Maybe some controllers in this device broke or something like that?

**Comment by xypron** [comment] 2017-12-09 14:21
@papachappa 
I obviously did not make the point.
I need the vendor and hardware id reported by lsusb for your Gembird to understand what is going wrong.

It is in the line reported by lsusb when your Gembird is plugged in and which is not reported by lsusb when it is not connected. Could you, please, send me that line.

**Comment by papachappa** [comment] 2017-12-10 10:03
We got a several such devices and three of them who can respond to lsub command have that:
"ID 04b4:fd13 Cypress Semiconductor Corp. Programmable power socket". I guess two of them who did not respond to lsusb have the same ouput. Is that info helpful?

**Comment by xypron** [comment] 2017-12-11 12:05
04b4:fd13 is a supported device.

If USB devices cannot be discovered by the operating system this is not a bug of sispmctl. So I close this issue.

**Closed as completed by xypron** 2017-12-11 12:05 UTC
